[buildPlans.iosevka-termlig-haskell]   # <iosevka-custom> is your plan name
family = "Iosevka TermLig Haskell"     # Font menu family name
design = ["termlig", "ligset-haskell"] # Customize styles
